language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - graphviz
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_DIR=build
        - APP_NAME=print-ip
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - pushd ~
        - git clone https://github.com/google/googletest.git
        - cd googletest
        - mkdir build && cd build
        - cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
        - make -j8
        - sudo make install
        - sudo ldconfig
        - sudo apt-get update -qq
        - popd
      cache:
        directories:
          - googletest/
      script:
        - mkdir -p ${BUILD_DIR}  && cd ${BUILD_DIR} 
        - cmake ..
        - cmake --build .
        # - cmake --build . --target test
        - cmake --build . --target package

      deploy:
        - provider: script
          skip_cleanup: true
          on:
            branch: main
          script:
            - curl -T ${APP_NAME}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/OTUS/helloworld/$TRAVIS_BUILD_NUMBER/${APP_NAME}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_API_KEY
          keep_history: true
          local_dir: html
          on:
            branch: main
          repo:
            k-morozov/otus-print-ip